metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

output.elasticsearch:
  hosts: ["https://10.0.2.15:9200"]
  protocol: "https"
  username: "elastic"
  password: "elastic123"
  ssl.certificate_authorities: /etc/metricbeat/elasticsearch-ca.pem
#  ssl.certificate: /etc/metricbeat/elasticsearch-ca.pem
#  ssl.key: /etc/metricbeat/

setup.kibana:
  host: "https://10.2.0.15:5601"

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~