filebeat.config:
  inputs:
    enabled: true
    path: ${path.config}/inputs.d/*.yml
    reload.enabled: true
    reload.period: 10s
  modules:
    enabled: true
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

filebeat.inputs:
- type: filestream
  id: logstash-filestream
  enabled: true
  paths:
    - /var/log/filebeat/*.ndjson

output.elasticsearch:
  hosts: ["https://10.0.2.15:9200"]
  username: "elastic"
  password: "elastic123"
  ssl.certificate_authorities: /etc/filebeat/elasticsearch-ca.pem
#  ssl.certificate: /etc/filebeat/
#  ssl.key: /etc/filebeat/

setup.kibana:
  host: "https://<kibana_node>:5601"

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~